import { GradeStatus, ApprovalState } from '../enums';

/** Exam result for a student in a course */
export interface ExamResult {
  id: string;
  studentId: string;
  courseOfferingId: string;
  courseCode: string;
  semesterId: string;
  grade: string;          // e.g., "A", "B+", "C", "F"
  gradePoint: number;     // 4.0, 3.67, 3.0, 0.0 etc.
  gradeStatus: GradeStatus;
  marks?: number;
  releasedAt: string;
  releasedBy: string;     // Exam Division user ID
}

/** Retake plan generated by the system */
export interface RetakePlan {
  id: string;
  studentId: string;
  failedCourses: RetakeCourse[];
  proposedRevisions: RetakeSemesterRevision[];
  approvalState: ApprovalState;
  projectedGraduation: string;
  generatedAt: string;
  reviewedBy?: string;
  approvedBy?: string;
}

/** A failed course in the retake backlog */
export interface RetakeCourse {
  courseId: string;
  courseCode: string;
  courseName: string;
  creditHours: number;
  failedInSemester: string;
  scheduledRetakeSemester?: string;
}

/** Proposed changes to a future semester */
export interface RetakeSemesterRevision {
  semesterNumber: number;
  calendarSemester: string;
  addedCourses: string[];      // Retake course IDs
  deferredCourses: string[];   // MQA courses pushed forward
  totalCredits: number;
}
